[kurmigo-dms]
user = dmsuser
group = dmsuser
listen = /run/php/kurmigo-dms.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500

chdir = /var/www/kurmigo-dms
php_admin_value[error_log] = /var/log/php8.3-fpm-kurmigo-dms.log
php_admin_flag[log_errors] = on
